version: '3.7'
services:
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db/:/docker-entrypoint-initdb.d